services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: codex-frontend-client
    ports:
      - "3000:80"
    environment:
      - CODEX=http://localhost:8080
    
  nginx:
    image: nginx:alpine
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8070:80"
    depends_on:
      - client