services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: codex-frontend-client
    ports:
      - "3000:80"
    environment:
      - codex_url=http://host.docker.internal:8080
    volumes:
        - ./deployment/nginx.template:/etc/nginx/templates/10-variables.conf.template:ro