# please use localhost:8080 for codex_url for local development (without marketplace)
services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: codex-frontend-client
    ports:
      - "3000:80"
    environment:
      - codex_url=${codex_url:-http://kubernetes.docker.internal:30003}
